from __future__ import annotations

import html
from typing import Any

import frappe
from frappe import _
from frappe.utils import cstr

from vetedge.services.dashboard_host_payload import get_dashboard_payload
from vetedge.services.report_export import (
	MIME_TYPES,
	_csv_bytes,
	_json_dict,
	_normalize_options,
	_pdf_bytes,
	_set_download_response,
	_xlsx_bytes,
)
from vetedge.services.reporting_capabilities import require_reporting_action


DASHBOARD_TITLES = {
	"executive": _("Executive Dashboard"),
	"clinical": _("Clinical Dashboard"),
	"financial": _("Financial Dashboard"),
	"practitioner_performance": _("Practitioner Performance Dashboard"),
	"branch_performance": _("Branch Performance Dashboard"),
	"inventory_dispensary": _("Inventory & Dispensary Dashboard"),
	"lab": _("Laboratory Dashboard"),
	"vaccination": _("Vaccination Dashboard"),
	"hospitalisation": _("Hospitalisation Dashboard"),
	"boarding": _("Boarding Dashboard"),
	"grooming": _("Grooming Dashboard"),
}


def _dashboard_key(value: str) -> str:
	key = cstr(value or "").strip()
	if key not in DASHBOARD_TITLES:
		frappe.throw(_("Unknown VetEdge dashboard."))
	return key


def _safe(value: Any) -> Any:
	if value is None:
		return ""
	if isinstance(value, (str, int, float, bool)):
		return value
	return str(value)


def _summary(payload: dict) -> list[dict]:
	cards = []
	for group in ("kpis", "collection_metrics", "health_indicators"):
		for item in payload.get(group) or []:
			if not isinstance(item, dict):
				continue
			cards.append(
				{
					"label": item.get("label") or item.get("title") or _("Metric"),
					"value": _safe(item.get("value")),
				}
			)
	return cards


def _rows(payload: dict, include_charts: bool = True) -> list[dict]:
	rows: list[dict] = []
	for card in _summary(payload):
		rows.append({"section": _("Summary"), "metric": card["label"], "value": card["value"], "detail": ""})

	for item in payload.get("revenue_composition") or []:
		if not isinstance(item, dict):
			continue
		rows.append(
			{
				"section": _("Revenue Composition"),
				"metric": item.get("label") or item.get("title") or _("Service"),
				"value": _safe(item.get("value")),
				"detail": _("Share: {0}%").format(_safe(item.get("share_percent"))),
			}
		)

	for alert in payload.get("alerts") or []:
		if not isinstance(alert, dict):
			continue
		rows.append(
			{
				"section": _("Alerts"),
				"metric": alert.get("title") or _("Attention"),
				"value": _safe(alert.get("supporting_metric")),
				"detail": alert.get("description") or "",
			}
		)

	for table in payload.get("supporting_tables") or []:
		if not isinstance(table, dict):
			continue
		section = table.get("title") or _("Detail")
		columns = table.get("columns") or []
		for row in table.get("rows") or []:
			if not isinstance(row, dict):
				continue
			pairs = []
			for column in columns:
				if not isinstance(column, dict):
					continue
				fieldname = column.get("fieldname")
				if not fieldname:
					continue
				pairs.append(f"{column.get('label') or fieldname}: {_safe(row.get(fieldname))}")
			rows.append(
				{
					"section": section,
					"metric": row.get("name") or row.get("branch") or row.get("practitioner") or _("Record"),
					"value": "",
					"detail": " · ".join(pairs),
				}
			)

	if include_charts:
		for chart in payload.get("charts") or []:
			if not isinstance(chart, dict):
				continue
			data = chart.get("data") or {}
			labels = data.get("labels") or []
			for dataset in data.get("datasets") or []:
				if not isinstance(dataset, dict):
					continue
				values = dataset.get("values") or []
				for index, label in enumerate(labels):
					rows.append(
						{
							"section": chart.get("title") or _("Chart"),
							"metric": label,
							"value": _safe(values[index] if index < len(values) else ""),
							"detail": dataset.get("name") or dataset.get("label") or "",
						}
					)
	return rows


def _matrix(title: str, filters: dict, payload: dict, options: dict) -> tuple[list[list[Any]], int]:
	matrix: list[list[Any]] = []
	if options.get("include_title"):
		matrix.append([title])
	if options.get("include_generated_metadata"):
		matrix.append([_("Generated"), frappe.utils.now_datetime().isoformat(sep=" ", timespec="seconds")])
		matrix.append([_("Generated By"), frappe.session.user])
	if options.get("include_filters"):
		for key, value in filters.items():
			if value not in (None, "", []):
				matrix.append([str(key).replace("_", " ").title(), _safe(value)])
	if options.get("include_summary"):
		for item in _summary(payload):
			matrix.append([item["label"], item["value"]])
	if matrix:
		matrix.append([])
	header_index = len(matrix)
	matrix.append([_("Section"), _("Metric"), _("Value"), _("Detail")])
	for row in _rows(payload, include_charts=bool(options.get("include_charts"))):
		matrix.append([row["section"], row["metric"], row["value"], row["detail"]])
	return matrix, header_index


def _print_html(title: str, filters: dict, payload: dict, options: dict) -> str:
	parts = [
		"<!doctype html><html><head><meta charset='utf-8'>",
		"<style>@page{margin:12mm}body{font-family:Arial,sans-serif;color:#172033;font-size:9pt}",
		"h1{font-size:17pt;margin:0 0 8px}.meta{color:#667085;margin-bottom:10px}",
		".summary{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.card{border:1px solid #dfe5ef;border-radius:6px;padding:6px 9px}",
		".card b{display:block;font-size:11pt}table{width:100%;border-collapse:collapse;margin-top:10px}",
		"th,td{border:1px solid #dfe5ef;padding:5px;vertical-align:top}th{background:#f3f5f8;text-align:left}</style></head><body>",
	]
	if options.get("include_title"):
		parts.append(f"<h1>{html.escape(title)}</h1>")
	if options.get("include_generated_metadata"):
		parts.append(f"<div class='meta'>{html.escape(str(frappe.utils.now_datetime()))} · {html.escape(frappe.session.user)}</div>")
	if options.get("include_filters"):
		filter_text = " · ".join(
			f"{html.escape(str(key).replace('_', ' ').title())}: {html.escape(str(value))}"
			for key, value in filters.items()
			if value not in (None, "", [])
		)
		if filter_text:
			parts.append(f"<div class='meta'>{filter_text}</div>")
	if options.get("include_summary"):
		parts.append("<div class='summary'>")
		for item in _summary(payload):
			parts.append(f"<div class='card'>{html.escape(str(item['label']))}<b>{html.escape(str(item['value']))}</b></div>")
		parts.append("</div>")
	parts.append("<table><thead><tr><th>Section</th><th>Metric</th><th>Value</th><th>Detail</th></tr></thead><tbody>")
	for row in _rows(payload, include_charts=bool(options.get("include_charts"))):
		parts.append("<tr>")
		for key in ("section", "metric", "value", "detail"):
			parts.append(f"<td>{html.escape(str(_safe(row.get(key))))}</td>")
		parts.append("</tr>")
	parts.append("</tbody></table></body></html>")
	return "".join(parts)


@frappe.whitelist()
@frappe.read_only()
def download_dashboard(dashboard_key: str, filters=None, options=None) -> None:
	key = _dashboard_key(dashboard_key)
	require_reporting_action(key, scope_type="dashboard", action="export")
	filters_dict = _json_dict(filters)
	export_options = _normalize_options(options)
	payload = get_dashboard_payload(key, filters_dict) or {}
	title = cstr(payload.get("title") or DASHBOARD_TITLES[key])
	matrix, header_index = _matrix(title, filters_dict, payload, export_options)
	file_format = export_options["format"]
	if file_format == "pdf":
		content = _pdf_bytes(_print_html(title, filters_dict, payload, export_options), export_options["orientation"])
	elif file_format == "csv":
		content = _csv_bytes(matrix)
	else:
		content = _xlsx_bytes(matrix, title, header_index, export_options["include_filters"])
	filename = f"VetEdge-{key.replace('_', '-')}-dashboard"
	_set_download_response(content, filename, file_format)


@frappe.whitelist()
@frappe.read_only()
def get_dashboard_print_html(dashboard_key: str, filters=None, options=None) -> str:
	key = _dashboard_key(dashboard_key)
	require_reporting_action(key, scope_type="dashboard", action="print")
	filters_dict = _json_dict(filters)
	print_options = _normalize_options(
		{
			"format": "pdf",
			"scope": "all_filtered",
			"include_title": True,
			"include_filters": True,
			"include_summary": True,
			"include_charts": True,
			"include_generated_metadata": True,
			**_json_dict(options),
		}
	)
	payload = get_dashboard_payload(key, filters_dict) or {}
	title = cstr(payload.get("title") or DASHBOARD_TITLES[key])
	return _print_html(title, filters_dict, payload, print_options)
