from __future__ import annotations

from dataclasses import asdict, dataclass


@dataclass(frozen=True)
class NotificationEventDefinition:
	event_key: str
	event_label: str
	category: str
	default_channels: tuple[str, ...]
	email_template: str | None
	audience: str
	default_enabled: bool
	description: str


def _event(
	event_key: str,
	event_label: str,
	category: str,
	default_channels: tuple[str, ...] = ("Email",),
	email_template: str | None = None,
	audience: str = "Internal Staff",
	default_enabled: bool = True,
	description: str = "",
) -> NotificationEventDefinition:
	return NotificationEventDefinition(
		event_key=event_key,
		event_label=event_label,
		category=category,
		default_channels=default_channels,
		email_template=email_template,
		audience=audience,
		default_enabled=default_enabled,
		description=description,
	)


NOTIFICATION_EVENT_REGISTRY: dict[str, NotificationEventDefinition] = {
	"appointment_created": _event(
		"appointment_created",
		"Appointment Created",
		"Appointment",
		email_template="VetEdge - Appointment Created",
		audience="Owner + Staff",
		description="Raised when an appointment is created in the system.",
	),
	"appointment_booked": _event(
		"appointment_booked",
		"Appointment Booked",
		"Appointment",
		email_template="VetEdge - Appointment Created",
		audience="Owner + Staff",
		description="Legacy alias used when an appointment booking is completed.",
	),
	"appointment_scheduled": _event(
		"appointment_scheduled",
		"Appointment Scheduled",
		"Appointment",
		email_template="VetEdge - Appointment Scheduled",
		audience="Owner + Staff",
		description="Raised when an appointment moves into Scheduled status.",
	),
	"appointment_confirmed": _event(
		"appointment_confirmed",
		"Appointment Confirmed",
		"Appointment",
		email_template="VetEdge - Appointment Confirmed",
		audience="Owner + Staff",
		description="Raised when an appointment is confirmed.",
	),
	"appointment_checked_in": _event(
		"appointment_checked_in",
		"Appointment Checked In",
		"Appointment",
		email_template="VetEdge - Appointment Checked In",
		audience="Internal Staff",
		description="Raised when a patient checks in for an appointment.",
	),
	"appointment_started": _event(
		"appointment_started",
		"Appointment Started",
		"Appointment",
		email_template="VetEdge - Appointment In Consultation",
		audience="Internal Staff",
		description="Raised when an appointment moves into consultation.",
	),
	"appointment_completed": _event(
		"appointment_completed",
		"Appointment Completed",
		"Appointment",
		email_template="VetEdge - Appointment Completed",
		audience="Owner + Staff",
		description="Raised when an appointment is completed.",
	),
	"appointment_rescheduled": _event(
		"appointment_rescheduled",
		"Appointment Rescheduled",
		"Appointment",
		email_template="VetEdge - Appointment Rescheduled",
		audience="Owner + Staff",
		description="Raised when an appointment is rescheduled.",
	),
	"appointment_cancelled": _event(
		"appointment_cancelled",
		"Appointment Cancelled",
		"Appointment",
		email_template="VetEdge - Appointment Cancelled",
		audience="Owner + Staff",
		description="Raised when an appointment is cancelled.",
	),
	"appointment_no_show": _event(
		"appointment_no_show",
		"Appointment No Show",
		"Appointment",
		email_template="VetEdge - Appointment No Show",
		audience="Internal Staff",
		description="Raised when an appointment is marked as No Show.",
	),
	"appointment_reminder": _event(
		"appointment_reminder",
		"Appointment Reminder",
		"Appointment",
		default_channels=("Email", "SMS", "WhatsApp"),
		email_template="VetEdge - Appointment Reminder",
		audience="Owner",
		description="Reminder sent before a scheduled appointment.",
	),
	"guest_booking_received": _event(
		"guest_booking_received",
		"Guest Booking Received",
		"Portal",
		email_template="VetEdge - Guest Booking Received",
		audience="Internal Staff",
		description="Placeholder event for guest booking intake notifications.",
	),
	"guest_appointment_request_received": _event(
		"guest_appointment_request_received",
		"Guest Appointment Request Received",
		"Portal",
		email_template="VetEdge - Guest Appointment Request Received",
		audience="Internal Staff",
		description="Raised when a guest submits an appointment request.",
	),
	"guest_appointment_ready_for_approval": _event(
		"guest_appointment_ready_for_approval",
		"Guest Appointment Ready For Approval",
		"Portal",
		email_template="VetEdge - Guest Appointment Ready For Approval",
		audience="Internal Staff",
		description="Raised when a guest appointment needs internal approval.",
	),
	"owner_appointment_request_received": _event(
		"owner_appointment_request_received",
		"Owner Appointment Request Received",
		"Portal",
		email_template="VetEdge - Owner Appointment Request Received",
		audience="Internal Staff",
		description="Raised when an owner requests an appointment from the portal.",
	),
	"registration_request_received": _event(
		"registration_request_received",
		"Registration Request Received",
		"Portal",
		email_template="VetEdge - Registration Request Received",
		audience="Internal Staff",
		description="Raised when a guest registration request is received.",
	),
	"registration_confirmed": _event(
		"registration_confirmed",
		"Registration Confirmed",
		"Portal",
		email_template="VetEdge - Registration Confirmed",
		audience="Owner",
		description="Raised when registration is confirmed for an owner or patient.",
	),
	"consultation_invoice_created": _event(
		"consultation_invoice_created",
		"Consultation Invoice Created",
		"Billing",
		email_template="VetEdge - Consultation Invoice Created",
		audience="Owner + Accounts",
		description="Canonical consultation invoice event for future routing.",
	),
	"invoice_created": _event(
		"invoice_created",
		"Invoice Created",
		"Billing",
		email_template="VetEdge - Invoice Created",
		audience="Owner + Accounts",
		description="Raised when a Sales Invoice is created from a VetEdge workflow.",
	),
	"payment_received": _event(
		"payment_received",
		"Payment Received",
		"Payment",
		email_template="VetEdge - Payment Received",
		audience="Owner + Accounts",
		description="Raised when payment is received against an invoice.",
	),
	"payment_pending": _event(
		"payment_pending",
		"Payment Pending",
		"Payment",
		email_template="VetEdge - Payment Pending",
		audience="Owner + Accounts",
		description="Placeholder event for pending payment follow-up flows.",
	),
	"payment_initiated": _event(
		"payment_initiated",
		"Payment Initiated",
		"Payment",
		email_template="VetEdge - Payment Initiated",
		audience="Owner + Accounts",
		description="Raised when a payment flow is initiated for an invoice.",
	),
	"payment_reminder": _event(
		"payment_reminder",
		"Payment Reminder",
		"Payment",
		default_channels=("Email", "SMS", "WhatsApp"),
		email_template="VetEdge - Payment Reminder",
		audience="Owner",
		description="Reminder event for outstanding invoice balances.",
	),
	"accounts_action_required": _event(
		"accounts_action_required",
		"Accounts Action Required",
		"Billing",
		email_template="VetEdge - Accounts Action Required",
		audience="Accounts",
		description="Raised when accounts must review an operational billing state.",
	),
	"consultation_awaiting_payment": _event(
		"consultation_awaiting_payment",
		"Consultation Awaiting Payment",
		"Consultation",
		email_template="VetEdge - Consultation Awaiting Payment",
		audience="Accounts + Internal Staff",
		description="Raised when a consultation is blocked pending payment.",
	),
	"consultation_sent_to_dispensary": _event(
		"consultation_sent_to_dispensary",
		"Consultation Sent To Dispensary",
		"Consultation",
		email_template="VetEdge - Consultation Sent To Dispensary",
		audience="Dispensary",
		description="Raised when a consultation is handed to the dispensary workflow.",
	),
	"consultation_ready_for_treatment": _event(
		"consultation_ready_for_treatment",
		"Consultation Ready For Treatment",
		"Consultation",
		email_template="VetEdge - Consultation Ready For Treatment",
		audience="Internal Staff",
		description="Raised when treatment can proceed for a consultation.",
	),
	"lab_order_created": _event(
		"lab_order_created",
		"Lab Order Created",
		"Lab",
		email_template="VetEdge - Lab Order Created",
		audience="Lab + Clinical Staff",
		description="Raised when a lab order is created.",
	),
	"lab_sample_collected": _event(
		"lab_sample_collected",
		"Lab Sample Collected",
		"Lab",
		email_template="VetEdge - Lab Sample Collected",
		audience="Lab + Clinical Staff",
		description="Raised when lab sample collection is recorded.",
	),
	"lab_result_entered": _event(
		"lab_result_entered",
		"Lab Result Entered",
		"Lab",
		email_template="VetEdge - Lab Result Entered",
		audience="Lab + Clinical Staff",
		description="Raised when lab results are entered.",
	),
	"lab_result_ready_for_review": _event(
		"lab_result_ready_for_review",
		"Lab Result Ready For Review",
		"Lab",
		email_template="VetEdge - Lab Result Ready For Review",
		audience="Doctor",
		description="Raised when a lab result is ready for clinical review.",
	),
	"dispensary_request_created": _event(
		"dispensary_request_created",
		"Dispensary Request Created",
		"Dispensary",
		email_template="VetEdge - Dispensary Request Created",
		audience="Dispensary",
		description="Placeholder event for future dispensary request creation flows.",
	),
	"dispensary_confirmed": _event(
		"dispensary_confirmed",
		"Dispensary Confirmed",
		"Dispensary",
		email_template="VetEdge - Dispensary Confirmed",
		audience="Dispensary + Clinical Staff",
		description="Canonical confirmation event for dispensary completion.",
	),
	"dispensary_confirmation_completed": _event(
		"dispensary_confirmation_completed",
		"Dispensary Confirmation Completed",
		"Dispensary",
		email_template="VetEdge - Dispensary Confirmed",
		audience="Dispensary + Clinical Staff",
		description="Raised when dispensary confirmation completes successfully.",
	),
	"stock_issue_failed": _event(
		"stock_issue_failed",
		"Stock Issue Failed",
		"Stock",
		email_template="VetEdge - Stock Issue Failed",
		audience="Dispensary + Admin",
		description="Canonical stock issue failure event for future routing.",
	),
	"dispensary_stock_issue_failed": _event(
		"dispensary_stock_issue_failed",
		"Dispensary Stock Issue Failed",
		"Stock",
		email_template="VetEdge - Stock Issue Failed",
		audience="Dispensary + Admin",
		description="Raised when dispensary stock issue posting fails.",
	),
	"expired_stock_blocked": _event(
		"expired_stock_blocked",
		"Expired Stock Blocked",
		"Stock",
		email_template="VetEdge - Expired Stock Blocked",
		audience="Dispensary + Admin",
		description="Canonical expired stock block event for future routing.",
	),
	"dispensary_expired_stock_blocked": _event(
		"dispensary_expired_stock_blocked",
		"Dispensary Expired Stock Blocked",
		"Stock",
		email_template="VetEdge - Expired Stock Blocked",
		audience="Dispensary + Admin",
		description="Raised when expired stock blocks a dispensary action.",
	),
	"insufficient_non_expired_stock": _event(
		"insufficient_non_expired_stock",
		"Insufficient Non-Expired Stock",
		"Stock",
		email_template="VetEdge - Insufficient Non-Expired Stock",
		audience="Dispensary + Admin",
		description="Canonical insufficient stock event for future routing.",
	),
	"dispensary_insufficient_non_expired_stock": _event(
		"dispensary_insufficient_non_expired_stock",
		"Dispensary Insufficient Non-Expired Stock",
		"Stock",
		email_template="VetEdge - Insufficient Non-Expired Stock",
		audience="Dispensary + Admin",
		description="Raised when only expired or insufficient stock is available.",
	),
	"vaccination_administered": _event(
		"vaccination_administered",
		"Vaccination Administered",
		"Vaccination",
		email_template="VetEdge - Vaccination Administered",
		audience="Owner + Clinical Staff",
		description="Raised when a vaccination record is administered.",
	),
	"vaccination_due_soon": _event(
		"vaccination_due_soon",
		"Vaccination Due Soon",
		"Vaccination",
		default_channels=("Email", "SMS", "WhatsApp"),
		email_template="VetEdge - Vaccination Due Soon",
		audience="Owner",
		description="Reminder event for an upcoming vaccination due date.",
	),
	"vaccination_overdue": _event(
		"vaccination_overdue",
		"Vaccination Overdue",
		"Vaccination",
		default_channels=("Email", "SMS", "WhatsApp"),
		email_template="VetEdge - Vaccination Overdue",
		audience="Owner",
		description="Reminder event for an overdue vaccination.",
	),
	"grooming_booking_created": _event(
		"grooming_booking_created",
		"Grooming Booking Created",
		"Grooming",
		email_template="VetEdge - Grooming Booking Created",
		audience="Owner + Grooming Staff",
		description="Canonical grooming booking event for future routing.",
	),
	"grooming_appointment_created": _event(
		"grooming_appointment_created",
		"Grooming Appointment Created",
		"Grooming",
		email_template="VetEdge - Grooming Booking Created",
		audience="Owner + Grooming Staff",
		description="Raised when a grooming appointment is created.",
	),
	"grooming_appointment_confirmed": _event(
		"grooming_appointment_confirmed",
		"Grooming Appointment Confirmed",
		"Grooming",
		email_template="VetEdge - Grooming Appointment Confirmed",
		audience="Owner + Grooming Staff",
		description="Raised when a grooming appointment is confirmed.",
	),
	"grooming_started": _event(
		"grooming_started",
		"Grooming Started",
		"Grooming",
		email_template="VetEdge - Grooming Started",
		audience="Grooming Staff",
		description="Raised when a grooming session moves into progress.",
	),
	"grooming_completed": _event(
		"grooming_completed",
		"Grooming Completed",
		"Grooming",
		email_template="VetEdge - Grooming Completed",
		audience="Owner + Grooming Staff",
		description="Raised when a grooming session is completed.",
	),
	"grooming_invoice_created": _event(
		"grooming_invoice_created",
		"Grooming Invoice Created",
		"Grooming",
		email_template="VetEdge - Grooming Invoice Created",
		audience="Owner + Accounts",
		description="Raised when a grooming invoice is created or updated.",
	),
	"boarding_reserved": _event(
		"boarding_reserved",
		"Boarding Reserved",
		"Boarding",
		email_template="VetEdge - Boarding Reserved",
		audience="Owner + Boarding Staff",
		description="Raised when a boarding booking is reserved.",
	),
	"boarding_checked_in": _event(
		"boarding_checked_in",
		"Boarding Checked In",
		"Boarding",
		email_template="VetEdge - Boarding Checked In",
		audience="Owner + Boarding Staff",
		description="Raised when boarding check-in is completed.",
	),
	"boarding_checked_out": _event(
		"boarding_checked_out",
		"Boarding Checked Out",
		"Boarding",
		email_template="VetEdge - Boarding Checked Out",
		audience="Owner + Boarding Staff",
		description="Raised when a boarding stay is checked out.",
	),
	"boarding_invoice_created": _event(
		"boarding_invoice_created",
		"Boarding Invoice Created",
		"Boarding",
		email_template="VetEdge - Boarding Invoice Created",
		audience="Owner + Accounts",
		description="Raised when a boarding invoice is created.",
	),
	"owner_complaint_created": _event(
		"owner_complaint_created",
		"Owner Complaint Created",
		"Portal",
		email_template="VetEdge - Owner Complaint Created",
		audience="Internal Staff",
		description="Placeholder event for future owner complaint intake.",
	),
	"invoice_pdf_available": _event(
		"invoice_pdf_available",
		"Invoice PDF Available",
		"Portal",
		email_template="VetEdge - Invoice PDF Available",
		audience="Owner",
		description="Raised when an invoice PDF is prepared for the owner experience.",
	),
	"role_bundle_applied": _event(
		"role_bundle_applied",
		"Role Bundle Applied",
		"System/Admin",
		email_template="VetEdge - Role Bundle Applied",
		audience="Admin",
		description="Raised when a VetEdge role bundle is applied to a user.",
	),
	"unauthorized_action_blocked": _event(
		"unauthorized_action_blocked",
		"Unauthorized Action Blocked",
		"System/Admin",
		email_template="VetEdge - Unauthorized Action Blocked",
		audience="Admin",
		default_enabled=False,
		description="Canonical event for blocked or unauthorized actions.",
	),
	"branch_access_blocked": _event(
		"branch_access_blocked",
		"Branch Access Blocked",
		"System/Admin",
		email_template="VetEdge - Unauthorized Action Blocked",
		audience="Admin",
		default_enabled=False,
		description="Raised when branch-scoped access is blocked.",
	),
	"patient_access_blocked": _event(
		"patient_access_blocked",
		"Patient Access Blocked",
		"System/Admin",
		email_template="VetEdge - Unauthorized Action Blocked",
		audience="Admin",
		default_enabled=False,
		description="Raised when patient access is blocked.",
	),
	"owner_patient_access_blocked": _event(
		"owner_patient_access_blocked",
		"Owner Patient Access Blocked",
		"System/Admin",
		email_template="VetEdge - Unauthorized Action Blocked",
		audience="Admin",
		default_enabled=False,
		description="Raised when owner access to a patient is blocked.",
	),
	"owner_consultation_access_blocked": _event(
		"owner_consultation_access_blocked",
		"Owner Consultation Access Blocked",
		"System/Admin",
		email_template="VetEdge - Unauthorized Action Blocked",
		audience="Admin",
		default_enabled=False,
		description="Raised when owner consultation access is blocked.",
	),
	"medical_history_access_blocked": _event(
		"medical_history_access_blocked",
		"Medical History Access Blocked",
		"System/Admin",
		email_template="VetEdge - Unauthorized Action Blocked",
		audience="Admin",
		default_enabled=False,
		description="Raised when medical history access is blocked.",
	),
	"lab_order_access_blocked": _event(
		"lab_order_access_blocked",
		"Lab Order Access Blocked",
		"System/Admin",
		email_template="VetEdge - Unauthorized Action Blocked",
		audience="Admin",
		default_enabled=False,
		description="Raised when lab order access is blocked.",
	),
	"invoice_access_blocked": _event(
		"invoice_access_blocked",
		"Invoice Access Blocked",
		"System/Admin",
		email_template="VetEdge - Unauthorized Action Blocked",
		audience="Admin",
		default_enabled=False,
		description="Raised when invoice access is blocked.",
	),
	"internal_payment_access_blocked": _event(
		"internal_payment_access_blocked",
		"Internal Payment Access Blocked",
		"System/Admin",
		email_template="VetEdge - Unauthorized Action Blocked",
		audience="Admin",
		default_enabled=False,
		description="Raised when an internal payment action is blocked.",
	),
	"dispensary_access_blocked": _event(
		"dispensary_access_blocked",
		"Dispensary Access Blocked",
		"System/Admin",
		email_template="VetEdge - Unauthorized Action Blocked",
		audience="Admin",
		default_enabled=False,
		description="Raised when dispensary access is blocked.",
	),
	"lab_request_blocked": _event(
		"lab_request_blocked",
		"Lab Request Blocked",
		"System/Admin",
		email_template="VetEdge - Unauthorized Action Blocked",
		audience="Admin",
		default_enabled=False,
		description="Raised when lab request creation is blocked.",
	),
	"lab_result_entry_blocked": _event(
		"lab_result_entry_blocked",
		"Lab Result Entry Blocked",
		"System/Admin",
		email_template="VetEdge - Unauthorized Action Blocked",
		audience="Admin",
		default_enabled=False,
		description="Raised when lab result entry is blocked.",
	),
	"lab_result_review_blocked": _event(
		"lab_result_review_blocked",
		"Lab Result Review Blocked",
		"System/Admin",
		email_template="VetEdge - Unauthorized Action Blocked",
		audience="Admin",
		default_enabled=False,
		description="Raised when lab result review is blocked.",
	),
	"grooming_appointment_access_blocked": _event(
		"grooming_appointment_access_blocked",
		"Grooming Appointment Access Blocked",
		"System/Admin",
		email_template="VetEdge - Unauthorized Action Blocked",
		audience="Admin",
		default_enabled=False,
		description="Raised when grooming appointment access is blocked.",
	),
	"grooming_session_create_blocked": _event(
		"grooming_session_create_blocked",
		"Grooming Session Create Blocked",
		"System/Admin",
		email_template="VetEdge - Unauthorized Action Blocked",
		audience="Admin",
		default_enabled=False,
		description="Raised when grooming session creation is blocked.",
	),
	"grooming_session_progress_blocked": _event(
		"grooming_session_progress_blocked",
		"Grooming Session Progress Blocked",
		"System/Admin",
		email_template="VetEdge - Unauthorized Action Blocked",
		audience="Admin",
		default_enabled=False,
		description="Raised when grooming session progress is blocked.",
	),
	"grooming_billing_blocked": _event(
		"grooming_billing_blocked",
		"Grooming Billing Blocked",
		"System/Admin",
		email_template="VetEdge - Unauthorized Action Blocked",
		audience="Admin",
		default_enabled=False,
		description="Raised when grooming billing actions are blocked.",
	),
	"role_bundle_management_blocked": _event(
		"role_bundle_management_blocked",
		"Role Bundle Management Blocked",
		"System/Admin",
		email_template="VetEdge - Unauthorized Action Blocked",
		audience="Admin",
		default_enabled=False,
		description="Raised when role bundle management is blocked.",
	),
	"role_bundle_apply_blocked": _event(
		"role_bundle_apply_blocked",
		"Role Bundle Apply Blocked",
		"System/Admin",
		email_template="VetEdge - Unauthorized Action Blocked",
		audience="Admin",
		default_enabled=False,
		description="Raised when role bundle application is blocked.",
	),
}


EMAIL_TEMPLATE_MAPPINGS: dict[str, str] = {
	event_key: event.email_template
	for event_key, event in NOTIFICATION_EVENT_REGISTRY.items()
	if event.email_template
}


def get_notification_event_registry() -> dict[str, NotificationEventDefinition]:
	return NOTIFICATION_EVENT_REGISTRY


def get_notification_event_definition(event_key: str) -> NotificationEventDefinition | None:
	return NOTIFICATION_EVENT_REGISTRY.get(event_key)


def get_notification_email_template(event_key: str) -> str | None:
	return EMAIL_TEMPLATE_MAPPINGS.get(event_key)


def serialize_notification_events() -> list[dict]:
	rows = []
	for event in NOTIFICATION_EVENT_REGISTRY.values():
		row = asdict(event)
		row["default_channels"] = list(event.default_channels)
		rows.append(row)
	return rows
