from __future__ import annotations

from contextlib import contextmanager
from copy import deepcopy

import frappe
from erpnext.accounts.party import _get_party_details, get_party_account
from erpnext.controllers.accounts_controller import get_taxes_and_charges


VETEDGE_BILLING_REMARK_PREFIXES = (
	"VetEdge billing session ",
	"ProcessEdge Veterinary billing session ",
)
_USER_CONTEXT_ATTRS = (
	"cache",
	"form_dict",
	"jenv_restricted",
	"jenv_unrestricted",
	"role_permissions",
	"new_doc_templates",
	"user_perms",
)


def is_vetedge_billing_core_invoice(doc) -> bool:
	"""Return True only for draft invoices generated by VetEdge Billing Core."""
	if not doc:
		return False
	remarks = str(doc.get("remarks") or "").strip()
	return any(remarks.startswith(prefix) for prefix in VETEDGE_BILLING_REMARK_PREFIXES)


@contextmanager
def system_account_resolution_context():
	"""Temporarily resolve an ERPNext Account as Administrator, then restore request state.

	ERPNext's ``get_party_account`` performs an explicit Account read/select
	permission check. A clinical user should not need Chart of Accounts visibility
	just because trusted VetEdge server code creates a draft registration invoice.

	The elevation is deliberately limited to account resolution. Invoice
	insert/save/submit, party details, price-list selection, taxes, and all other
	Sales Invoice processing continue under the original actor.
	"""
	local = frappe.local
	original_session = deepcopy(local.session)
	original_attrs = {
		name: getattr(local, name)
		for name in _USER_CONTEXT_ATTRS
		if hasattr(local, name)
	}
	try:
		frappe.set_user("Administrator")
		yield
	finally:
		local.session = original_session
		for name, value in original_attrs.items():
			setattr(local, name, value)


def resolve_vetedge_receivable_account(customer: str, company: str) -> str:
	"""Resolve the canonical ERPNext receivable account without exposing Account to the actor."""
	if not customer or not company:
		frappe.throw(
			"Customer and Company are required before VetEdge can create a draft Sales Invoice.",
			frappe.ValidationError,
		)

	with system_account_resolution_context():
		account = get_party_account("Customer", customer, company)

	if not account:
		frappe.throw(
			f"A Receivable Account is required for customer {customer} in company {company}.",
			frappe.ValidationError,
		)
	return account


def apply_customer_defaults_without_account_lookup(invoice, for_validate: bool = False) -> None:
	"""Apply normal customer defaults while deliberately skipping party-account lookup.

	ERPNext's ``_get_party_details`` performs the Account permission check only for
	invoice doctypes. Calling it without an invoice doctype preserves the logged-in
	user's Customer, Address and Price List permission context while avoiding the
	duplicate Account lookup. ``SalesInvoice.set_missing_values`` already resolved
	``debit_to`` and ``due_date`` before this method is reached.
	"""
	customer = getattr(invoice, "customer", None)
	if not customer:
		return

	party_details = _get_party_details(
		customer,
		account=invoice.get("debit_to"),
		company=invoice.company,
		posting_date=invoice.get("posting_date"),
		doctype=None,
		ignore_permissions=invoice.flags.ignore_permissions,
		fetch_payment_terms_template=invoice.has_value_changed("company"),
		party_address=invoice.get("customer_address"),
		shipping_address=invoice.get("shipping_address_name"),
		company_address=invoice.get("company_address"),
	)
	# Defensive: a future ERPNext change must not overwrite the trusted account or
	# due date resolved by the Sales Invoice controller before this helper runs.
	party_details.pop("debit_to", None)
	party_details.pop("due_date", None)
	if not invoice.meta.get_field("sales_team"):
		party_details.pop("sales_team", None)
	invoice.update_if_missing(party_details)

	if invoice.get("taxes_and_charges") and not invoice.get("taxes") and not for_validate:
		for tax in get_taxes_and_charges("Sales Taxes and Charges Template", invoice.taxes_and_charges):
			invoice.append("taxes", tax)


class VetEdgeSalesInvoiceBillingMixin:
	"""Narrow ERPNext Sales Invoice extension for VetEdge Billing Core drafts.

	Normal/manual Sales Invoices retain standard ERPNext permission behaviour.
	Only Billing Core-generated invoices receive server-owned receivable-account
	resolution. Standard Sales Invoice validation, create/write permissions,
	accounting validation, pricing permissions, and submit controls remain intact.
	"""

	def set_missing_values(self, for_validate: bool = False):
		if not is_vetedge_billing_core_invoice(self):
			return super().set_missing_values(for_validate)

		if not self.get("debit_to") and self.get("customer") and self.get("company"):
			self.debit_to = resolve_vetedge_receivable_account(self.customer, self.company)
			self.party_account_currency = frappe.db.get_value(
				"Account",
				self.debit_to,
				"account_currency",
				cache=True,
			)

		# ERPNext SalesInvoice.set_missing_values now sees debit_to and skips its
		# direct get_party_account call. The SellingController callback below keeps
		# the user's normal party/price-list permission context.
		return super().set_missing_values(for_validate)

	def set_missing_lead_customer_details(self, for_validate: bool = False):
		if not is_vetedge_billing_core_invoice(self):
			return super().set_missing_lead_customer_details(for_validate)
		return apply_customer_defaults_without_account_lookup(self, for_validate)
