from __future__ import annotations

from contextlib import contextmanager
from copy import deepcopy

import frappe
from erpnext.accounts.party import get_party_account


VETEDGE_BILLING_REMARK_PREFIXES = (
	"VetEdge billing session ",
	"ProcessEdge Veterinary billing session ",
)
_USER_CONTEXT_ATTRS = (
	"cache",
	"form_dict",
	"jenv_restricted",
	"jenv_unrestricted",
	"role_permissions",
	"new_doc_templates",
	"user_perms",
)


def is_vetedge_billing_core_invoice(doc) -> bool:
	"""Return True only for draft invoices generated by VetEdge Billing Core.

	This intentionally does not match ordinary ERPNext Sales Invoices. The
	Billing Core marker exists before ``set_missing_values`` runs, which lets us
	resolve ERPNext defaults without widening Account permissions for clinical
	users.
	"""
	if not doc:
		return False
	remarks = str(doc.get("remarks") or "").strip()
	return any(remarks.startswith(prefix) for prefix in VETEDGE_BILLING_REMARK_PREFIXES)


@contextmanager
def system_default_resolution_context():
	"""Temporarily resolve ERPNext defaults as Administrator, then restore request state.

	ERPNext's ``get_party_account`` performs an explicit Account read/select
	permission check even when a document is being populated by trusted server
	code. VetEdge clinical users should not need Chart of Accounts visibility just
	because Billing Core creates a draft invoice automatically.

	The elevation is deliberately scoped to default resolution only. It does not
	cover Sales Invoice insert/save/submit, and the complete Frappe request/user
	context that ``frappe.set_user`` resets is restored in ``finally``.
	"""
	local = frappe.local
	original_session = deepcopy(local.session)
	original_attrs = {
		name: getattr(local, name)
		for name in _USER_CONTEXT_ATTRS
		if hasattr(local, name)
	}
	try:
		frappe.set_user("Administrator")
		yield
	finally:
		local.session = original_session
		for name, value in original_attrs.items():
			setattr(local, name, value)


def resolve_vetedge_receivable_account(customer: str, company: str) -> str:
	"""Resolve the ERPNext receivable account without exposing Account to the actor."""
	if not customer or not company:
		frappe.throw(
			"Customer and Company are required before VetEdge can create a draft Sales Invoice.",
			frappe.ValidationError,
		)

	with system_default_resolution_context():
		account = get_party_account("Customer", customer, company)

	if not account:
		frappe.throw(
			f"A Receivable Account is required for customer {customer} in company {company}.",
			frappe.ValidationError,
		)
	return account


class VetEdgeSalesInvoiceBillingMixin:
	"""Narrow ERPNext Sales Invoice extension for VetEdge Billing Core drafts.

	Normal/manual Sales Invoices retain standard ERPNext permission behaviour.
	Only invoices marked as Billing Core-generated receive server-side party and
	account default resolution. Standard Sales Invoice validation, create/write
	permissions, accounting validation, and submit controls remain unchanged.
	"""

	def set_missing_values(self, for_validate: bool = False):
		if not is_vetedge_billing_core_invoice(self):
			return super().set_missing_values(for_validate)

		if not self.get("debit_to") and self.get("customer") and self.get("company"):
			self.debit_to = resolve_vetedge_receivable_account(self.customer, self.company)
			self.party_account_currency = frappe.db.get_value(
				"Account",
				self.debit_to,
				"account_currency",
				cache=True,
			)

		# SalesInvoice.set_missing_values will now skip its direct get_party_account
		# call. SellingController still resolves customer/party details separately;
		# our override below scopes only that ERPNext default lookup as system-owned.
		return super().set_missing_values(for_validate)

	def set_missing_lead_customer_details(self, for_validate: bool = False):
		if not is_vetedge_billing_core_invoice(self):
			return super().set_missing_lead_customer_details(for_validate)
		with system_default_resolution_context():
			return super().set_missing_lead_customer_details(for_validate)
